In [14]:
# Import Libraries

import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\nehat\OneDrive\Desktop\CF DA Immersion\Achievement 4\Instacart Basket Analysis 09'

In [3]:
# Import Dataset

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'new_variables.pkl'))

In [4]:
# Create a subset

df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 19)

In [6]:
df.head(10)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days
0,0,2539329,1,prior,1,2,8,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
1,1,2398795,1,prior,2,3,7,15.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
2,2,473747,1,prior,3,3,12,21.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
3,3,2254736,1,prior,4,4,7,29.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
4,4,431534,1,prior,5,4,15,28.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
5,5,3367565,1,prior,6,2,7,19.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
6,6,550135,1,prior,7,1,9,20.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
7,7,3108588,1,prior,8,1,14,14.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
8,8,2295261,1,prior,9,1,16,0.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy
9,9,2550362,1,prior,10,4,8,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy

In [7]:
df.groupby('product_name')

In [8]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [10]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [12]:
# perform multiple aggregations

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

## 2. Create a loyalty flag using loc

In [15]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [16]:
ords_prods_merge.head(15)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,max_order
0,0,2539329,1,prior,1,2,8,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
1,1,2398795,1,prior,2,3,7,15.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
2,2,473747,1,prior,3,3,12,21.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
3,3,2254736,1,prior,4,4,7,29.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
4,4,431534,1,prior,5,4,15,28.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
5,5,3367565,1,prior,6,2,7,19.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
6,6,550135,1,prior,7,1,9,20.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
7,7,3108588,1,prior,8,1,14,14.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
8,8,2295261,1,prior,9,1,16,0.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
9,9,2550362,1,prior,10,4,8,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
10,144,2968173,15,prior,15,1,9,7.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
11,146,1870022,15,prior,17,2,16,8.000000,196,6,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
12,147,1911383,15,prior,18,2,11,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
13,150,2715276,15,prior,21,1,9,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
14,151,487368,15,prior,22,1,10,14.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22

In [17]:
ords_prods_merge.head(100)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,max_order
0,0,2539329,1,prior,1,2,8,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
1,1,2398795,1,prior,2,3,7,15.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
2,2,473747,1,prior,3,3,12,21.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
3,3,2254736,1,prior,4,4,7,29.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
4,4,431534,1,prior,5,4,15,28.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5895,3226575,360,prior,1,5,12,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,3
96,6137,1469869,377,prior,3,5,17,3.000000,196,9,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,3
97,6259,1927023,387,prior,2,4,10,22.000000,196,3,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,8
98,6740,858092,420,prior,4,1,19,30.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
99,6741,119314,420,prior,5,3,19,16.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22

In [18]:
pd.options.display.max_rows = None

In [19]:
ords_prods_merge.head(100)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,max_order
0,0,2539329,1,prior,1,2,8,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
1,1,2398795,1,prior,2,3,7,15.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
2,2,473747,1,prior,3,3,12,21.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
3,3,2254736,1,prior,4,4,7,29.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
4,4,431534,1,prior,5,4,15,28.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
5,5,3367565,1,prior,6,2,7,19.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
6,6,550135,1,prior,7,1,9,20.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
7,7,3108588,1,prior,8,1,14,14.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
8,8,2295261,1,prior,9,1,16,0.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
9,9,2550362,1,prior,10,4,8,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,10
10,144,2968173,15,prior,15,1,9,7.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
11,146,1870022,15,prior,17,2,16,8.000000,196,6,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
12,147,1911383,15,prior,18,2,11,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
13,150,2715276,15,prior,21,1,9,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
14,151,487368,15,prior,22,1,10,14.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
15,209,2293453,19,prior,2,5,14,6.000000,196,3,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,9
16,212,1973799,19,prior,5,6,12,8.000000,196,15,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,9
17,214,532817,19,prior,7,4,17,6.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,9
18,232,1573906,21,prior,10,3,10,6.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,33
19,458,1593000,31,prior,10,3,8,7.000000,196,17,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,20
20,465,2231262,31,prior,17,3,11,8.000000,196,14,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,20
21,617,2580647,43,prior,6,4,16,4.000000,196,9,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,11
22,620,2187180,43,prior,9,4,12,3.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,11
23,751,2497897,52,prior,1,1,9,1.111484,196,4,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
24,752,1318871,52,prior,2,1,10,7.000000,196,5,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
25,753,1261384,52,prior,3,1,10,7.000000,196,3,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
26,755,580568,52,prior,5,2,10,8.000000,196,6,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
27,757,2428073,52,prior,7,2,7,8.000000,196,5,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
28,759,342306,52,prior,9,1,11,7.000000,196,5,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
29,760,1520353,52,prior,10,2,10,8.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
30,761,2542086,52,prior,11,2,9,7.000000,196,3,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
31,762,944694,52,prior,12,1,16,6.000000,196,7,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
32,765,1268191,52,prior,15,2,11,8.000000,196,3,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
33,767,1122089,52,prior,17,2,10,6.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
34,768,1498922,52,prior,18,2,10,14.000000,196,6,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
35,769,180919,52,prior,19,3,8,8.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
36,771,2695875,52,prior,21,5,10,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,27
37,1022,3205960,67,prior,1,3,11,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
38,1023,970922,67,prior,2,1,15,5.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
39,1024,596585,67,prior,3,1,13,7.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
40,1025,2037087,67,prior,4,2,9,8.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
41,1026,2474111,67,prior,5,3,14,8.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
42,1027,1568481,67,prior,6,3,12,7.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
43,1029,2048527,67,prior,8,2,11,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
44,1030,2389031,67,prior,9,2,14,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
45,1031,2378562,67,prior,10,1,10,6.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
46,1032,1515698,67,prior,11,1,11,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
47,1033,1928050,67,prior,12,2,12,8.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
48,1034,1949274,67,prior,13,1,10,6.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
49,1035,551869,67,prior,14,1,9,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
50,1037,768572,67,prior,16,4,10,9.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
51,1039,150528,67,prior,18,5,16,4.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
52,1040,29758,67,prior,19,0,14,9.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Busiest days,24
53,1042,1558976,67,prior,21,1,9,5.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
54,1043,863974,67,prior,22,1,11,14.000000,196,3,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
55,1044,2308399,67,prior,23,1,14,14.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,24
56,1202,2759128,81,prior,3,1,9,14.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,7
57,1204,1812985,81,prior,5,2,20,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,7
58,1208,1889835,82,prior,1,3,15,1.111484,196,6,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
59,1210,499460,82,prior,3,5,10,5.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
60,1211,2728456,82,prior,4,0,11,16.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Busiest days,19
61,1213,2653743,82,prior,6,4,9,13.000000,196,5,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
62,1216,1358880,82,prior,9,1,10,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
63,1217,343588,82,prior,10,2,11,1.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
64,1222,3034663,82,prior,15,2,11,12.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
65,1225,147262,82,prior,18,1,13,7.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
66,1226,3144004,82,prior,19,2,15,8.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,19
67,1480,2126069,98,prior,3,0,9,25.000000,196,7,0,both,195,Soda,77,7,9.0,Mid-range product,Busiest days,14
68,1484,2210120,98,prior,7,5,14,5.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,14
69,1486,681011,98,prior,9,3,9,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,14
70,1488,2846344,98,prior,11,4,13,15.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,14
71,1489,747431,98,prior,12,6,13,30.000000,196,4,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,14
72,1490,2383054,98,prior,13,4,11,30.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,14
73,1491,1993729,98,prior,14,5,8,8.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,14
74,1608,1403849,109,prior,3,3,17,9.000000,196,5,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,6
75,1744,520620,120,prior,1,3,11,1.111484,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,3
76,1746,3273029,120,prior,3,2,8,19.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,3
77,2781,1861943,185,prior,2,1,12,25.000000,196,10,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,6
78,2891,2040988,195,prior,1,1,14,1.111484,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
79,2898,1680569,195,prior,8,1,9,4.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
80,2909,276171,195,prior,19,5,11,3.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
81,2912,2744976,195,prior,22,5,10,7.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
82,2915,2781919,195,prior,25,1,14,4.000000,196,1,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
83,2921,1738718,195,prior,31,2,8,4.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
84,2924,3058369,195,prior,34,3,10,6.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
85,2927,1485596,195,prior,37,2,15,0.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
86,2930,417035,195,prior,40,3,16,2.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
87,2937,1615297,195,prior,47,5,10,2.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
88,2942,1765587,195,prior,52,3,12,2.000000,196,3,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
89,2947,745908,195,prior,57,4,11,3.000000,196,3,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,58
90,3451,2505656,222,prior,17,2,12,1.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,70
91,3472,3268370,222,prior,38,5,15,1.000000,196,6,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,70
92,4667,2016711,290,prior,9,5,19,6.000000,196,8,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,51
93,4686,2706088,290,prior,28,6,10,7.000000,196,16,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,51
94,5551,1952286,331,prior,6,5,16,30.000000,196,8,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,8
95,5895,3226575,360,prior,1,5,12,1.111484,196,1,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,3
96,6137,1469869,377,prior,3,5,17,3.000000,196,9,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,3
97,6259,1927023,387,prior,2,4,10,22.000000,196,3,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,8
98,6740,858092,420,prior,4,1,19,30.000000,196,2,0,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22
99,6741,119314,420,prior,5,3,19,16.000000,196,2,1,both,195,Soda,77,7,9.0,Mid-range product,Regularly busy,22

In [20]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [21]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [22]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [23]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: loyalty_flag, dtype: int64

In [27]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3